# Generated by Django 4.2 on 2023-05-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_information_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
