# Generated by Django 4.2 on 2023-05-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_information_is_bio_alter_information_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
