# Generated by Django 4.2 on 2023-05-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_album_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='information',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
