# Generated by Django 4.2 on 2023-05-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='liked_albums',
        ),
    ]
