# Generated by Django 4.2 on 2023-05-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_userprofile_liked_albums'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liked_albums',
            field=models.ManyToManyField(blank=True, to='core.album'),
        ),
    ]
