# Generated by Django 4.2 on 2023-05-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_liked_albums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
